name: build
on:
- push
jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
        - Ubuntu
        - Windows
        - MacOS
    steps:
    - name: Test Expression
      run: echo ${{ matrix.os == "Windows" }}
