name: Test Action

on: workflow_dispatch

jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform:
        - runner: windows-latest
          os: windows
          zip: 7z a
        - runner: ubuntu-latest
          os: linux
          zip: zip
    runs-on: ${{ matrix.platform.runner }}
    steps:
    - name: Install zip
      if: ${{ matrix.platform.os == 'windows' }} 
      run: |
        choco install zip
    - name: Prepare
      shell: bash
      run: |
        echo Hello, world >hi.txt
        chmod ugo=rx hi.txt
        ls -l
    - name: Zip
      shell: bash
      run: |
        # Compress-Archive hi.txt hi.zip
        # zip -9 hi.zip hi.txt
        ${{ matrix.platform.zip }} hi.zip hi.txt
    - name: Check results
      shell: bash
      run: |
        rm hi.txt
        unzip hi.zip
        ls -l
