name: build
#on:
#    schedule:
#    - cron: "30 12 * * 0"
jobs:
    get_vim:
        name: get_vim
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@master
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                python-version: 3.8
            - name: Build Vim
              id: build
              run: python vim.py all
            - name: Create Release
              id: create_release
              uses: ncipollo/release-action@v1
              with:
                tag: ${{ steps.build.outputs.version }}
                commit: master
                allowUpdates: true
                artifacts: "vim*.zip*"
                token: ${{ secrets.GITHUB_TOKEN }}
