name: build
on: push
jobs:
    get_vim:
        name: get_vim
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@master
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                python-version: 3.8
            - name: Step 1
              run: |
                  $vs = (dir 'C:\Program Files*\Microsoft Visual Studio\*\*\Common7\Tools\VsDevCmd.bat').FullName
                  "`"$vs`" & build.bat" | cmd
